### ISSUE TITLE
Using Background Control Options Manually

### ISSUE THREAD

**Issue by ericakfranz** [aristath/kirki#15]
I'm wondering if there's a way to use use the background control options manually instead of having them automatically generated and output as an inline style? I'm already generating an inline style and would like to just combine everything in one so there aren't two separate inline styles in the head.

For example, using like this results in nothing -

$sfpbg = get_theme_mod( 'sfp_bg' );
$cssoutput = '';
    if ( $sfpbg ) {
        $cssoutput .=
            ".page-template-front-page-php .site-header { " . $sfpbg . " } \n";
    }
if ( $cssoutput ) {
        echo 
            "<style type=\"text/css\">" . $cssoutput . "</style>";
}

However, I'm able to make other controls output properly with this method, just not the Background Control.

Not sure how to fix the appearance of the quot areas above, but those are style tags.

**Comment by aristath** [comment]
Hey there!

I'm sorry for the extreme delay here...
Do you still require assistance on this issue?

**Comment by ericakfranz** [comment]
Ha, we all get busy! ;)

Yes, if there is a solution or work around if still love to implement it.

Thanks!

**Comment by aristath** [comment]
Hello again!

If you want to omit the default styles output then you can simply omit the`'output'` argument.
The background control actually creates 7 separate theme_mods that you can use:

```
my_setting_color
my_setting_image
my_setting_repeat
my_setting_size
my_setting_attach
my_setting_position
my_setting_opacity
```

We had to do it this way because it's almost impossible to save an array using the customizer...  
So if you want to get the background color, you'd do it like this:

``` php
<?php $bg_color = get_theme_mod( 'my_setting_color', '#ffffff' ); ?>
```

It's all described in detail on the kirki docs site: http://kirki.org/#background

I hope that helps!
