### ISSUE TITLE
How about Panels?

### ISSUE THREAD

**Issue by karloestrada** [aristath/kirki#25]
Kirki looks really easy to use. However, does it supports creation of "Panels"?

**Comment by aristath** [comment]
You can create panels and sections the normal WP way.
Kirki focuses on the settings themselves, nothing more than that. :smile:

**Comment by karloestrada** [comment]
Hello Aristeides! Thanks for the reply. Appreciate it. Sorry one more question...can I also use outside classes for control? Let's say google web fonts into a select options or typekit fonts? 

I'll start integrating kirki to my project. This convinced me!

Karlo Estrada
I make websites

Website: http://www.digitalmohawk.com | Email: karlo@digitalmohawk.com
m: +61 423720873
skype: moyger

**Comment by karloestrada** [comment]
I integrated the kirki to my theme. However, is there a way that I can use the default look/css of the customizer? Not the dark theme? I understand that it has been overwritten but can we use the default theme?

Karlo Estrada
I make websites

Website: http://www.digitalmohawk.com | Email: karlo@digitalmohawk.com
m: +61 423720873
skype: moyger

**Comment by karloestrada** [comment]
Oh just found out...all settings are set in type => "theme_mod". Is there an configuration that we can set this to "option".

The reason is let's say I chose multicheck control and I want to retrieve option 2, how can I retrieve that using get_theme_mod? I think only way is to use get_option['option_2']. 

Thanks in advance!

Karlo Estrada
I make websites

Website: http://www.digitalmohawk.com | Email: karlo@digitalmohawk.com
m: +61 423720873
skype: moyger

**Comment by aristath** [comment]
> can I also use outside classes for control? Let's say google web fonts into a select options or typekit fonts?

Sure you can!
That's what I'm also doing in my own projects!

> However, is there a way that I can use the default look/css of the customizer? Not the dark theme? I understand that it has been overwritten but can we use the default theme?

If you installed the plugin from WordPress.org then please just use the master branch of this repository. This has already been fixed and will be included in the next plugin update.

> all settings are set in type => "theme_mod". Is there an configuration that we can set this to "option"

Currently I'm afraid not. This is something in our to-do list, but is not a priority right now.

> The reason is let's say I chose multicheck control and I want to retrieve option 2, how can I retrieve that using get_theme_mod? I think only way is to use get_option['option_2'].

Actually the customizer doesn't allow us to save an array as a theme_mod, so instead the settings are converted to CSV in order to properly be saved in the database.
You can get the saved values just fine, all it needs is an extra line of code.
I use something like this on my own themes:

``` php
$my_option = explode( ',', get_theme_mod( 'my_multicheck_setting' ) );

$option_1 = $my_option['option_1'];
$option_2 = $my_option['option_2'];
```
