### ISSUE TITLE
Remove styling

### ISSUE THREAD

**Issue by jmslbam** [aristath/kirki#9]
Hi Aristeides,

First of all, thank you very very much for this, I really enjoy it!

I have a question about the custom styling. Somehow, I can't seem to be able to remove this action to I can keep the default WordPress styling.

`add_action( 'customize_controls_print_styles', array( $this, 'custom_css' ), 999 );`

I have tried a bunch, like a lot, of combinations starting from this:
`remove_action( 'customize_controls_print_styles', array('Kirki', 'custom_css'), 1000 );`

I even editied the plugin creating the `Kriki` on `wp_admin` and stuff like that. Maybe it's because it's Fridayafternoon and it's beer o'clock. But I can't get it to work.

Hope you can help me with this little issue.

Ciao!

**Comment by jmslbam** [comment]
Same goes for `wp_enqueue_style( 'kirki-customizer-css')`.
https://github.com/aristath/kirki/blob/master/kirki.php#L64

**Comment by aristath** [comment]
Hey there!

It's been a long time since this issue...
We recently removed most of the styles and now by default use the selected admin color scheme for the current user instead.

Are you still having this issue?
We're looking into minimizing the effect the plugin has on the customizer (visually), so I'd love to hear your opinion on it!

**Comment by jmslbam** [comment]
Hola, we haven't been using it because we started using the Options page of ACF because I had to concetrate all settings in 1 place / menu. But removing all styling and using the default is / sounds great.
When I do need a theme-custimizer again I will use Kirki again!

Gracias
